main:
  bin: "__app_bin_path__/rdiff-backup"
  # bin: "echo"
backups:
  - name: "example"
    source: "/private/tmp"
    dest: "user@backupfriend::/backup/media/usb/example"
    port: "8022"
    key: "__user_data__/id_rsa"
    server_username: admin
    server_url: http://backupfriend
    every: "daily"
    time: "08:00"
