name: Package Application for Mac OS X
on: [push, pull_request]


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [macos-latest]
    steps:
      - uses: actions/checkout@master
      - name: Install rdiff-backup
        run: |
          brew update
          brew install python@3.9
          brew install rdiff-backup
          brew install wxpython
          brew install libyaml
          brew upgrade
      - name: Display Brew path
        run: brew --prefix
      - name: which python3
        run: which python3
      - name: Display Python version
        run: python3 -c "import sys; print(sys.version)"
      - name: Install py2app
        run: python3 -m pip install py2app
      - name: upgrade pip
        run: python3 -m pip install --upgrade pip
      - name: install rdiff-backup via pip
        run: python3 -m pip install rdiff-backup
      - name: install requirements.txt
        run: python3 -m pip install -r requirements.txt
      - name: Build app
        run: python3 setup.py py2app
      - name: Codesign executable
        env:
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_ID: ${{ secrets.MACOS_CERTIFICATE_ID }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
        run: |
          echo ${MACOS_CERTIFICATE} | base64 --decode > certificate.p12
          echo A
          security create-keychain -p build.keychain build.keychain1
          echo B
          security default-keychain -s build.keychain1
          echo C
          security unlock-keychain -p build.keychain build.keychain1
          echo D
          security import certificate.p12 -k build.keychain1 -P ${MACOS_CERTIFICATE_PWD} -T /usr/bin/codesign
          echo E
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k build.keychain build.keychain1
          echo F
          echo G
          /usr/bin/codesign --force --deep -s "Developer ID Application: Guy Sheffer (K8784SVNX8)" dist/BackupFriend.app -v
          echo H
          /usr/bin/codesign --force --deep -s "Developer ID Application: Guy Sheffer (K8784SVNX8)" dist/BackupFriend.app/Contents/Frameworks/Python.framework/Versions/Current -v
          /usr/bin/codesign --force --deep -s "Developer ID Application: Guy Sheffer (K8784SVNX8)" dist/BackupFriend.app/Contents/Frameworks/Python.framework -v
          /usr/bin/codesign --verify --verbose dist/BackupFriend.app
          tar czvf dist/BackupFriend.tar.gz dist/BackupFriend.app
          rm -rf dist/BackupFriend.app
          rm -fr *.p12
      - uses: actions/upload-artifact@v2
        with:
          name: backupfriend-client-macos
          path: dist/
